### ISSUE TITLE
Improvement of Private Icon

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-issue-tracker#398]
The private icon design from Sam hides the preview of the viz itself ( in the latest viz on my profile page). This design has a lock and a text "private". Isn't lock an icon for private?
![Screenshot from 2020-07-17 13-10-31](https://user-images.githubusercontent.com/13540669/87813159-5c8d3e80-c82f-11ea-9d5e-aedac2f88350.png)

**Comment by curran** [comment]
Any suggestions?

I have some ideas:
 * Make it smaller
 * Make it semi-transparent

Thoughts?

**Comment by nitanagdeote** [comment]
The word 'private' does not seem to be required.
