### ISSUE TITLE
sort option "oldest"

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-issue-tracker#404]
(originally opened by @nitanagdeote )

**Comment by curran** [comment]
I think we can frame this as "ascending" vs. "descending", and apply it to any of the sort options.

So there would be another UI element that lets you toggle sort order.

**Comment by curran** [comment]
Although, "oldest" pertains I guess to the "created date", not the "last updated date"... Hmmmm. So maybe this should be its own thing actually.

**Comment by nitanagdeote** [comment]
May be
