### ISSUE TITLE
Notes / Annotations

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-issue-tracker#444]
From @nitanagdeote:
>Writing notes in viz page. A text file like google doc or similar.

Core idea: have a space where you can take notes on what the code means or why it is there.

Solution ideas (what's already present):
 * Comments in code
 * README.md

Solution ideas (new development):
 * Something like GitHub's Pull Request "comment on line" feature.
 * Comments https://github.com/datavis-tech/vizhub-issue-tracker/issues/17

**Comment by curran** [comment]
Fresh ideas and example from @sriramvsharma  - https://via.hypothes.is/https://github.com/sriramvsharma/vizhub-code-annotations/blob/master/Let's%20make%20a%20map%20with%20D3.js!/index.js#annotations:group:__world__

![image](https://user-images.githubusercontent.com/68416/89047036-ce7b8280-d31b-11ea-99ec-4c7e328c856b.png)

**Comment by curran** [comment]
Researching this tool https://via.hypothes.is/ , pasting screenshots here for UI design inspiration.

The tool can annotate any page.

![image](https://user-images.githubusercontent.com/68416/89047268-316d1980-d31c-11ea-98f8-b47c31b3ad9b.png)

Highlighting some text gives this popup UI:

![image](https://user-images.githubusercontent.com/68416/89047419-61b4b800-d31c-11ea-9437-5b3dd7a80d54.png)

![image](https://user-images.githubusercontent.com/68416/89047524-8577fe00-d31c-11ea-8fb3-a2ce650352b9.png)

**Comment by sriramvsharma** [comment]
I really like the genre of "The Anatomy of" style content for explaining code grammar and logic. Wish there was a VScode plugin for it! Some examples: 

https://daneden.me/blog/2020/anatomy-of-a-typed-react-component
http://apps.workflower.fi/vocabs/css/en#comment
https://wattenberger.com/blog/react-and-d3

**Comment by sriramvsharma** [comment]
Genius does annotation particularly well too. https://genius.com/20469400

**Comment by curran** [comment]
Rough thoughts for first design iteration: there can be an "annotations mode" in VizHub that you can enter and exit.

Main idea: we want to preserve the current experience of editing code (e.g. selecting a block of text could trigger some annotation entry point, but maybe only in "annotations mode", so that it doesn't distract from regular coding activities).

**Comment by curran** [comment]
Amazing design work from @sriramvsharma here https://xd.adobe.com/view/30dd4bb8-3f31-431b-7e5f-6287bcb98fbb-46ec/screen/a0c21deb-c4a2-4695-8fe4-f0bc93370a67/

**Comment by curran** [comment]
I love the entry point design, as it does not interfere at all with existing design/layout/features.

![image](https://user-images.githubusercontent.com/68416/90050857-cd940a80-dca4-11ea-8310-02a5c4e14c30.png)

**Comment by curran** [comment]
Really cool idea to replace the entire right panel.

![image](https://user-images.githubusercontent.com/68416/90050938-e8ff1580-dca4-11ea-9db3-7cccbf724122.png)

**Comment by curran** [comment]
Nice editing UI. Maybe we can re-use some design ideas from #17 .

![image](https://user-images.githubusercontent.com/68416/90051175-4e530680-dca5-11ea-8298-3f32559f5676.png)

Also maybe the upvote and downvote icons can be the same as for viz upvoting and downvoting.

**Comment by curran** [comment]
Great ideas for the share UI!

![image](https://user-images.githubusercontent.com/68416/90051305-7f333b80-dca5-11ea-8778-2b27665de028.png)

**Comment by curran** [comment]
One more idea from @stushurik 

![image](https://user-images.githubusercontent.com/68416/90653622-68dd3080-e20d-11ea-9fb2-d71530cbf907.png)

>it's from github. seems like it parses source code and show some insights on hover
