### ISSUE TITLE
Home page Hero section

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-issue-tracker#453]
Playing around the homepage design. 
https://www.figma.com/file/NaFUw2i60j5ggFvcX6tfFk/mapHeroSEctionVizhub?node-id=0%3A1

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/90047310-b69ee980-dc9f-11ea-8414-41c8ebea5b6c.png)

Idea: we try the new Embed feature and embed a viz that looks like this into the home page itself.
