### ISSUE TITLE
We need resources link in navigation bar

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-issue-tracker#535]
![TABLEAU](https://user-images.githubusercontent.com/13540669/97489418-e91ec100-1935-11eb-8c54-148115dad4a0.png)

**Comment by curran** [comment]
Resources can maybe be a pinned page in the forum.

Links to tutorials

VizHub or D3? Both?

Someone who is using VizHub - what information they need.

Link to datavis 2020, 2018 version

"Getting started" - good nomenclature

Quick how-to

Get up to speed

D3 Slack - help
