### ISSUE TITLE
Reference examples

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-issue-tracker#601]
In d3 help somebody asked about zoomable maps. I wish we had an example which I could post as an answer.

**Comment by curran** [comment]
Here's one https://vizhub.com/curran/4fb5e4e665474a169325bd18cdc3d0c0

Ideas for improovement:

 * Create a big index of all examples, sorted by technique
 * Create a blog post (with attached discussion thread) for each individual technique
