### ISSUE TITLE
Design Mobile Navbar with Hamburger Menu

### ISSUE THREAD

**Issue by nitanagdeote** [vizhub-core/vizhub-issue-tracker#624]
Did anybody notice there are no nav bar links on mobile?

**Comment by stushurik** [comment]
there is no space for links in mobile view. we need to come up with a mobile design, my we can use a hamburger menu

**Comment by nitanagdeote** [comment]
We can make logo size small. At least one link of pricing should be there.Hamburger menu is required.

**Comment by nitanagdeote** [comment]
We made issue for hamburger menu long time back.

**Comment by curran** [comment]
Design inspiration from [Forbes](https://www.forbes.com/sites/bernardmarr/2018/06/20/comparing-data-visualization-software-here-are-the-7-best-tools-for-2018/?sh=10e5a6506d0b) (shared previously by @nitanagdeote ) in #420:

![image](https://user-images.githubusercontent.com/68416/101370641-bdb5bd00-3877-11eb-85d5-b1137c6119a3.png)

![image](https://user-images.githubusercontent.com/68416/101370720-d6be6e00-3877-11eb-821b-5c87a18d1e28.png)

**Comment by curran** [comment]
Done in v3. See https://vizhub.community
