### ISSUE TITLE
Custom Viz URLs

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-issue-tracker#693]
As a viz author, I want to be able to give a viz a custom URL, so that it can be more easily referenced.

For example, I want to make an alias to this link:

https://vizhub.com/curran/469e558ba77941aa9e1b416ea521b0aa

that looks like this:

https://vizhub.com/curran/html-starter

**Comment by stushurik** [comment]
@curran also app should handle gracefully errors and warning,e.g. user tries to create the same alias twice

**Comment by curran** [comment]
Yes, that's definitely a consideration.

Similar to choosing a user name "That is already taken, please choose another".
