### ISSUE TITLE
Autocomplete and/or offline editing

### ISSUE THREAD

**Issue by laurajchang** [vizhub-core/vizhub-issue-tracker#731]
I've been enjoying using VizHub, but quickly became frustrated that there was no autocomplete for variable names, parentheses, etc. If this could be incorporated into the text editor and/or there could be compatibility with other offline text editors of the user's choice, I think the experience would be greatly enhanced.

**Comment by curran** [comment]
There is CTRL+Space autocomplete at the moment.

![image](https://user-images.githubusercontent.com/68416/109435972-2fbb1f80-79eb-11eb-9140-b8515186ef0e.png)

One thing we can do for this is make sure that the keyboard combination is documented.

The offline idea is interesting. Like local storage in the browser? Or the ability to import from exported and modified files? Related to #268 .

**Comment by stushurik** [comment]
@curran, maybe vizhub might have some level of "smart" autocomplete? As far as I understood, it suggests something based on plain text (e.g., if there are some word is present). It would be great if vizhub might make suggestions based on javascript context, e.g., suggest imports, object properties e.t.c

**Comment by curran** [comment]
I agree those would be excellent improvements to make! I believe the autocomplete just looks at existing words in the file you are editing. One extension of that would be to look for words across all files in the viz (tracked as #306 ).

**Comment by curran** [comment]
This is done in https://github.com/vizhub-core/vzcode
